language: python
python:
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- "./test.bash"
deploy:
  provider: pypi
  on:
    tags: true
  skip_existing: true
  user: __token__
  password:
    secure: RD79NVGtzRwc5GpC64GmgokVQRn303TczsRjoSwQT/kcJLwJ6LRdcnmqjSWg/Dij2COis5RlaRK80noq9x6Z4bTC7ghagWrX3eO678v5c300TjNFmqdbg94z+6Bdg5rlb/KlOBUDO4Lv+tR0V08wX5sQcXzyBdoSarHA2QIFIS9MCJbLjuavV/8ahsNqXyIZE4m63n1BoLYqBcI97F2WOSXbwCGfrstb/pk5LqULgJT3fyUhsheQ33fVXrQyZn9u6HKF0aX5XS4oMZ1lS4aZPqZ7PyJXxi7npyQ7yoq9axkLls7mwhCoqXcF5DUsGAkF0oCjjCbIoUzX+PSnQZCb5qNrhqmfO1mGd+ETe93BJNYjeQM7d1cFAXJwC0jlkk+Bp3MGKRQUXOlnvplyoSg9ZlLu7YOMemd9rXZwROdbwh/XuaeEoyRDHgJ5oMHtIeT5d3qQrQhaEa0YN/INAybac3r27Errq21iMD7w7RMJ4+lGMQm4gRSI8OQiGElbjxF2trX5MUX8eysS8618iTve3LKgCvPyBwlLX22oyG6J8tQ6xn9WNq48hhYzvacXACw+2HnzDdU/Ky/N6TkcSDF0MqUre6s1XEgK8dlXVSEgrUFEXfefL7XtHESHEUPDJUrsUGDLq5mvu9loBCom68qMzysK7w/qm7wzAn4o4VZnm7w=
